//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicNamespace.Repositories
{
    using System;
    using System.Collections.Generic;
    using MongoDB.Driver;
    
    
    public class DynamicRepository : IDynamicRepository
    {
        
        private static IMongoCollection<dynamic> GetMongoCollection()
        {
var client = new MongoClient(GetMongoConnectionString());
var database = client.GetDatabase("YourDatabaseName");
return database.GetCollection<dynamic>("YourCollectionName");
        }
        
        private static List<dynamic> FetchDataFromMongoDB()
        {
var collection = GetMongoCollection();
var documents = collection.Find(_ => true).ToList();
return documents;
        }
        
        private static void SaveDataToMongoDB(dynamic data)
        {
var collection = GetMongoCollection();
collection.InsertOne(data);
        }
    }
}
