//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicNamespace.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Http;
    using DynamicNamespace.Services;
    
    
    public class DynamicController : ApiController
    {
        
        private IDynamicService _service;
        
        public DynamicController(IDynamicService service)
        {
_service = service;
        }
        
        [HttpGet()]
        public virtual List<dynamic> FetchData()
        {
return _service.FetchData();
        }
        
        [HttpPost()]
        public virtual void SaveData(dynamic data)
        {
_service.SaveData(data);
        }
    }
}
