//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicNamespace.Services
{
    using System;
    using System.Collections.Generic;
    using DynamicNamespace.Repositories;
    
    
    public class DynamicService : IDynamicService
    {
        
        private IDynamicRepository _repository;
        
        public DynamicService(IDynamicRepository repository)
        {
_repository = repository;
        }
        
        public override List<dynamic> FetchData()
        {
return _repository.GetAll();
        }
        
        public override void SaveData(dynamic data)
        {
_repository.Save(data);
        }
    }
}
