//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicNamespace.Services
{
    using System;
    using System.Collections.Generic;
    using DynamicNamespace.Repositories;
    
    
    public class IDynamicService
    {
        
        public virtual List<dynamic> FetchData()
        {
        }
        
        public virtual void SaveData(dynamic data)
        {
        }
    }
}
