//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicNamespace.Repositories
{
    using System;
    using System.Collections.Generic;
    using MongoDB.Driver;
    
    
    public class IDynamicRepository
    {
        
        public virtual List<dynamic> GetAll()
        {
        }
        
        public virtual void Save(dynamic data)
        {
        }
    }
}
